/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ADC_base 	0x50000000UL

#define ADC_offset 	0x08UL

#define ADC1_CR 	(ADC_base+ADC_offset)

#define RCC_offset 0x14UL

#define RCC_base 0x40021000UL

#define RCC_ADC (RCC_offset+RCC_base)

int main(void)
{
    /* Loop forever */
	uint32_t *rcc= (uint32_t*) RCC_ADC;
	uint32_t *adc1 = (uint32_t*) ADC1_CR;
	*rcc|=(1<<28);
	*adc1|=1;
	for(;;);
}
